# .github/workflows/deploy.yml

name: Loark CI/CD for Private EC2

on:
  push:
    branches: [ "master" ]
  # PULL REQUEST 트리거 제거
  # pull_request:
  #   branches: [ "master" ]

jobs:
  #########################################
  # 1. Docker 이미지를 빌드하고 ECR에 푸시 #
  #########################################
  build-and-push-to-ecr:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build-image.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        working-directory: ./Loark
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./Loark
        run: ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./Loark
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  #############################################
  # 2. EC2에 접속하여 새 Docker 컨테이너를 실행 #
  #############################################
  deploy-to-ec2:
    needs: build-and-push-to-ecr
    runs-on: ubuntu-latest

    steps:
    - name: Debug SSH Connection  # 👈 이 코드로 완전히 교체합니다.
      run: |
        # 1. 시크릿으로 받은 Private Key를 파일로 저장합니다.
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        # 2. 아주 상세한 로그(-vvv)를 출력하며 SSH 접속을 시도합니다.
        ssh -o StrictHostKeyChecking=no \
            -vvv \
            -i private_key.pem \
            ec2-user@${{ secrets.BASTION_HOST }} \
            "echo 'SSH 접속 성공!'"
